config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'todo#index', as: 'todo_index'
  get '/tambah', to: 'todo#tambah', as: 'todo_tambah'
  post '/tambah/kirim', to: 'todo#kirim', as: 'todo_kirim'
  get '/:id/edit', to: 'todo#edit', as: 'todo_edit'
  patch '/:id/edit/update', to: 'todo#update', as: 'todo_update'
  get '/:id/delete', to: 'todo#destroy', as: 'todo_destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController

    def index
        @tasks = Todo.all
    end

    def tambah
        @tambah = Todo.new
    end

    def kirim
        @kirim = Todo.new(todo_params)

        if @kirim.save

            redirect_to todo_index_path, notice: 'Task berhasil ditambahkan'
        else

            render :tambah
        end
        
    end

    def edit
        @ambil_id = Todo.find(params[:id])
    end

    def update
        @ambil_id = Todo.find(params[:id])

        if @ambil_id.update(todo_params)
            
            redirect_to todo_index_path, notice: 'Task berhasil diupdate'
        else

            render :edit
        end
        
    end

    def destroy
        @ambil_id = Todo.find(params[:id])

        if @ambil_id.destroy

            redirect_to todo_index_path, notice: 'Task berhasil dihapus'
        else
            
            render :index
        end
        
    end

    private
    def todo_params
        params.require(:todo).permit(:task, :deadline, :status)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo/edit.html.erb
<%= link_to 'kembali', todo_index_path %>

<br><br>

<%= form_with model: @ambil_id, url: todo_update_path do |f| %>

    <label>Task</label><br>
    <%= f.text_field :task, placeholder: 'nama task' %>
    <br><br>

    <label>Deadline</label><br>
    <%= f.date_field :deadline %>
    <br><br>

    <label>Status</label><br>
    <%= f.select :status, [['Selesai', true], ['Belum Selesai', false]] %>
    <br><br>

    <%= f.submit 'Update' %>
<% end %>

app/views/todo/index.html.erb
<% if notice %>
    <%= notice %>
<% end %>

<br><br>

<%= link_to 'tambah task', todo_tambah_path %>

<br><br>

<table border="1">    
    <thead>
        <tr>
            <th>No</th>
            <th>Task</th>
            <th>Deadline</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @tasks.each_with_index do |data, index| %>
        <tr>
            <td ><%= index+=1 %></td>
            <td><%= data.task %></td>
            <td><%= data.deadline %></td>
            <td>
                <% if data.status? %>
                    Selesai
                <% else %>
                    Belum Selesai
                <% end %>
            </td>
            <td>
            <%= link_to 'Hapus', todo_destroy_path(data.id), data: { confirm: 'Ingin menghapus task ini?' }, method: :delete %>
            <%= link_to 'Edit', todo_edit_path(data.id) %>            
        </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/todo/tambah.html.erb
<%= link_to 'kembali', todo_index_path %>

<br><br>

<%= form_with model: @tambah, url: todo_kirim_path do |f| %>

    <label>Task</label><br>
    <%= f.text_field :task, placeholder: 'nama task'%>
    <br><br>

    <label>Deadline</label><br>
    <%= f.date_field :deadline %>
    <br><br>

    <label>Status</label><br>
    <%= f.select :status,[['Selesai', true], ['Belum Selesai', false]]%>
    <br><br>

    <%= f.submit 'Tambah'%>
<% end %>